load("@rules_cc//cc:defs.bzl", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_test(
    name = "message_queue_test",
    srcs = ["message_queue_test.cpp"],
    copts = ["-std=c++20"],
    linkstatic = True,
    deps = [
        "//include/cytoskeleton/itc/message_queue:message_queue",
        "@googletest//:gtest",
    ],
)
